### ISSUE TITLE
[feature](general): spin up Ceramic Mainnet Node

### ISSUE THREAD

**Issue by martines3000** [blockchain-lab-um/masca#339]
### Summary

- [x] Choose hosting provider
- [x] Set up Docker and Ceramic Testnet
- [x] [Access mainnet](https://composedb.js.org/docs/0.4.x/guides/composedb-server/access-mainnet)

**Comment by pseudobun** [comment]
Inquiry has been sent to [netcup](https://netcup.eu/) for their VPS 4000 G10 [found on this page](https://www.netcup.eu/vserver/vps.php). The providers we've been choosing from can be found in this [sheet](https://docs.google.com/spreadsheets/d/1zyUQiLXuEYX5I0e0qUvB2dkKx7NEhFfWPpIuoOYEN_c/edit?usp=sharing).

**Comment by pseudobun** [comment]
Node is up and running. Switch to our own API endpoint will be closed in: #414.
