### ISSUE TITLE
[bug](snap): getting error while resolving a did:ethr on sepolia

### ISSUE THREAD

**Issue by radleylewis** [blockchain-lab-um/masca#543]
## Issue Overview

When resolving a did `did:ethr:sepolia` using the masca `resolveDID` rpc method, the following error is returned:

```
"Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="changed(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)"
```

## Other Context

This error indicates that the did does not exist/has not been created. However, when instantiating the Veramo agent within a nodejs runtime, it resolves. 

### To Reproduce

Invoke masca rpc resolveDid

### Expected behavior

The rpc call should resolve the provided did document.

**Comment by martines3000** [comment]
Hi. Thank you for reporting the issue.

With which version of Veramo did you test this ?

**Comment by radleylewis** [comment]
Hey, thanks for your response. I am using the below veramo version:
```json
"@veramo/did-comm": "5.5.4-next.32"
```
I have raised a PR with the fix (#545)

**Comment by martines3000** [comment]
Hi. We are using the latest Veramo version 5.5.3.

I updated the all the Veramo package versions yesterday (to 5.5.4-next.32), but I still need to test if everything works correctly now.
If I don't encounter any new issues, I will create a new beta release of Masca today.

**Comment by radleylewis** [comment]
Appreciate it. Thanks @martines3000!

**Comment by martines3000** [comment]
Hey @radleylewis. I created a new release (v1.2.0-beta.2) available here: 

https://www.npmjs.com/package/@blockchain-lab-um/masca/v/1.2.0-beta.2

You will need MetaMask Flask for this version. You can test it on our [beta dapp](https://beta.masca.io)
